### ISSUE TITLE
Sample fileformat validator hook doesn't work as intended

### ISSUE THREAD

**Issue by vinodhini-sd** [treeverse/lakeFS-hooks#10]
Irrespective of the format of files under the specific prefix, the hook always fails. 
> TODO: Need to evaluate the other hooks as well.

**Comment by nopcoder** [comment]
@vinodhini8694 do you have the hooks server output/look or the status code returned from the hook? Or even the log from the lakeFS server side in other to get more information about the reason why the hook failed?
Also which data / operation - is it was merge or commit? pre hook?

**Comment by nopcoder** [comment]
@vinodhini-sd can I close this one?

**Comment by vinodhini-sd** [comment]
Note: The file format validator hook failed due to a [port issue](https://github.com/treeverse/lakeFS-samples/pull/14). 

Closing this.
